# Generated by Django 4.1.5 on 2023-01-25 09:46

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="blog",
            options={"verbose_name": "Блог", "verbose_name_plural": "Блоги"},
        ),
        migrations.AlterModelOptions(
            name="category",
            options={"verbose_name": "Категорія", "verbose_name_plural": "Категорії"},
        ),
        migrations.AlterModelOptions(
            name="comment",
            options={"verbose_name": "Коментар", "verbose_name_plural": "Коментарі"},
        ),
        migrations.AlterModelOptions(
            name="reply",
            options={"verbose_name": "Відповідь", "verbose_name_plural": "Відповіді"},
        ),
        migrations.AlterModelOptions(
            name="tag",
            options={"verbose_name": "Тег", "verbose_name_plural": "Теги"},
        ),
        migrations.AlterField(
            model_name="blog",
            name="banner",
            field=models.ImageField(upload_to="blog_banners", verbose_name="Банер"),
        ),
        migrations.AlterField(
            model_name="blog",
            name="category",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="category_blogs",
                to="blog.category",
                verbose_name="Категорія",
            ),
        ),
        migrations.AlterField(
            model_name="blog",
            name="created_date",
            field=models.DateField(auto_now_add=True, verbose_name="Дата створення"),
        ),
        migrations.AlterField(
            model_name="blog",
            name="description",
            field=ckeditor.fields.RichTextField(verbose_name="Опис"),
        ),
        migrations.AlterField(
            model_name="blog",
            name="likes",
            field=models.ManyToManyField(
                blank=True,
                related_name="user_likes",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Подобається",
            ),
        ),
        migrations.AlterField(
            model_name="blog",
            name="slug",
            field=models.SlugField(blank=True, null=True, verbose_name="URL"),
        ),
        migrations.AlterField(
            model_name="blog",
            name="tags",
            field=models.ManyToManyField(
                blank=True, related_name="tag_blogs", to="blog.tag", verbose_name="Теги"
            ),
        ),
        migrations.AlterField(
            model_name="blog",
            name="title",
            field=models.CharField(max_length=250, verbose_name="Заголовок"),
        ),
        migrations.AlterField(
            model_name="blog",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="user_blogs",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Користувач",
            ),
        ),
        migrations.AlterField(
            model_name="category",
            name="created_date",
            field=models.DateField(auto_now_add=True, verbose_name="Дата створення"),
        ),
        migrations.AlterField(
            model_name="category",
            name="slug",
            field=models.SlugField(blank=True, null=True, verbose_name="URL"),
        ),
        migrations.AlterField(
            model_name="category",
            name="title",
            field=models.CharField(
                max_length=150, unique=True, verbose_name="Заголовок"
            ),
        ),
        migrations.AlterField(
            model_name="comment",
            name="blog",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="blog_comments",
                to="blog.blog",
                verbose_name="Блог",
            ),
        ),
        migrations.AlterField(
            model_name="comment",
            name="created_date",
            field=models.DateTimeField(
                auto_now_add=True, verbose_name="Дата створення"
            ),
        ),
        migrations.AlterField(
            model_name="comment",
            name="text",
            field=models.TextField(verbose_name="Зміст"),
        ),
        migrations.AlterField(
            model_name="comment",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="user_comments",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Користувач",
            ),
        ),
        migrations.AlterField(
            model_name="reply",
            name="comment",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="comment_replies",
                to="blog.comment",
                verbose_name="Коментар",
            ),
        ),
        migrations.AlterField(
            model_name="reply",
            name="created_date",
            field=models.DateTimeField(
                auto_now_add=True, verbose_name="Дата створення"
            ),
        ),
        migrations.AlterField(
            model_name="reply",
            name="text",
            field=models.TextField(verbose_name="Зміст"),
        ),
        migrations.AlterField(
            model_name="reply",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="user_replies",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Користувач",
            ),
        ),
        migrations.AlterField(
            model_name="tag",
            name="created_date",
            field=models.DateField(auto_now_add=True, verbose_name="Дата створення"),
        ),
        migrations.AlterField(
            model_name="tag",
            name="slug",
            field=models.SlugField(blank=True, null=True, verbose_name="URL"),
        ),
        migrations.AlterField(
            model_name="tag",
            name="title",
            field=models.CharField(max_length=150, verbose_name="Заголовок"),
        ),
    ]
